package assingnMentPackage;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class FriendsAssi {
	public static void main(String[] args) throws InterruptedException {
	WebDriver	driver=new ChromeDriver();
	driver.manage().window().maximize();
	driver.get("https://www.google.com/");
	Thread.sleep(2000);
	driver.findElement(By.id("APjFqb")).sendKeys("Joey Tribbiani");
	Thread.sleep(2000);
	driver.get("https://www.google.com/search?q=joey+tribbiani&rlz=1C1CHBD_enIN1057IN1057&oq=&aqs=chrome.0.69i59i450l8.575362745j0j15&sourceid=chrome&ie=UTF-8");
    //driver.findElement(By.id("APjFqb")).sendKeys("rodd geller");
   //driver.findElement(By.id("APjFqb")).sendKeys("chandler bing");
	//Thread.sleep(2000);
	//driver.findElement(By.name("btnK")).click();
	Thread.sleep(2000);
	driver.findElement(By.className("lNPNe")).click();
	Thread.sleep(4000);
	driver.get("https://www.google.com/search?q=phoebe+buffay&rlz=1C1CHBD_enIN1057IN1057&ei=Dnq3ZLDiOY2WseMPmou0iAQ&oq=&gs_lp=Egxnd3Mtd2l6LXNlcnAiACoCCAAyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQRIjFdQiANY3Q9wAngBkAEAmAHVAaABuwiqAQUwLjQuMrgBAcgBAPgBAagCFMICChAAGEcY1gQYsAPCAgoQABiKBRiwAxhDwgIOEAAY5AIY1gQYsAPYAQHCAhAQLhiKBRjIAxiwAxhD2AECwgIOEAAYigUYsQMYgwEYkQLCAggQABiKBRiRAsICCBAuGIoFGJECwgIFEC4YgATCAgUQABiABMICBxAAGIoFGEPCAgcQLhiKBRhDwgILEC4YigUYsQMYgwHCAggQLhiABBixA8ICCxAAGIAEGLEDGIMB4gMEGAAgQYgGAZAGEboGBggBEAEYCboGBggCEAEYCLoGBAgDGAe6BgYIBBABGAo&sclient=gws-wiz-serp");
	Thread.sleep(2000);
	driver.findElement(By.className("lNPNe")).click();
	Thread.sleep(2000);
	driver.get("https://www.google.com/search?q=chandler+bing&rlz=1C1CHBD_enIN1057IN1057&ei=B363ZImuOc2useMPp8y54A4&oq=&gs_lp=Egxnd3Mtd2l6LXNlcnAiACoCCAAyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyEBAAGIoFGOoCGLQCGEPYAQMyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQQyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQRItosNUABYAHAGeAGQAQCYAQCgAQCqAQC4AQHIAQD4AQGoAhTCAgoQABhHGNYEGLADwgIKEAAYigUYsAMYQ8ICDhAAGOQCGNYEGLAD2AEBwgIQEC4YigUYyAMYsAMYQ9gBAuIDBBgAIEGIBgGQBhK6BgYIARABGAm6BgYIAhABGAi6BgQIAxgHugYGCAQQARgK&sclient=gws-wiz-serp");
	Thread.sleep(2000);
	driver.findElement(By.className("lNPNe")).click();
	Thread.sleep(2000);
	driver.get("https://www.google.com/search?q=monica+geller&rlz=1C1CHBD_enIN1057IN1057&ei=4n63ZLPyF_a7seMPmMCk-AE&oq=&gs_lp=Egxnd3Mtd2l6LXNlcnAiACoCCAIyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAuGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQJI1BRQAFgAcAF4AZABAJgBAKABAKoBALgBAcgBAPgBAagCFOIDBBgAIEGIBgG6BgQIARgHugYGCAIQARgK&sclient=gws-wiz-serp");
	Thread.sleep(2000);
	driver.findElement(By.className("lNPNe")).click();
	Thread.sleep(2000);
	driver.get("https://www.google.com/search?q=ross+geller&rlz=1C1CHBD_enIN1057IN1057&ei=1IG3ZKK0O9usseMPvoavyAw&oq=&gs_lp=Egxnd3Mtd2l6LXNlcnAiACoCCAQyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAuGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyEBAAGIoFGOoCGLQCGEPYAQEyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAuGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQIyFhAAGAMYjwEY6gIYtAIYjAMY5QLYAQJI4jZQAFgAcAF4AZABAJgBAKABAKoBALgBAcgBAPgBAagCFOIDBBgAIEGIBgG6BgQIARgHugYGCAIQARgK&sclient=gws-wiz-serp");
	Thread.sleep(2000);
	driver.findElement(By.className("lNPNe")).click();
	driver.close();
	
	
	}

}
